### ISSUE TITLE
Is it real Emulator?

### ISSUE THREAD

**Issue by NS-Clone** [azya52/BrickEmuPy#1]
Is it real Emulator?
where i can get die shots/reverse information/discussion threads etc?

**Comment by azya52** [comment]
Hi, yes, this is a real emulator.
There is an article in Russian, you can see it in machine translation https://habr-com.translate.goog/ru/articles/773040/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp&_x_tr_hist=true

**Comment by NS-Clone** [comment]
да я и так могу :)
надо тогда внятно написать в readme.md
а то это из разряда прорыв/наконец свершилось

**Comment by azya52** [comment]
Добавил ссылку :)
