### ISSUE TITLE
Additional ROMs?

### ISSUE THREAD

**Issue by yellowberryHN** [azya52/BrickEmuPy#10]
As I was reading through your article, I noticed that you had a picture of multiple generations of the brick game MCU. Have you been able to translate those yet, or are they still in progress?

I have an E-9999 BB-664 model, and I was wondering if you happened to have one of those. I don't have the necessary equipment (microscope) to be able to do the ROM extraction myself, so I was hoping you would have one.

**Comment by azya52** [comment]
Unfortunately, I can't read the ROM in these chips. In fact, as I now understand, after decapsulating a large number of games, visually readable ROM can only be found in very few. E-9999 and BB-664 are modern versions of Brick Game, it is most likely impossible to read their ROM.

**Comment by yellowberryHN** [comment]
Thank you for your reply! That is quite unfortunate, but I understand. I am still very happy to see this project exist at all, however!
