### ISSUE TITLE
how to build E23PlusMarkII96in1.asm? 

### ISSUE THREAD

**Issue by predefine** [azya52/BrickEmuPy#3]
how to build E23PlusMarkII96in1.asm to E23PlusMarkII96in1.bin ?

**Comment by azya52** [comment]
I haven't developed assembler for this mcu, so no way for now.

**Comment by NS-Clone** [comment]
> I haven't developed an assembler for this mcu, so no way for now.

вроде как в tasm-е можно быстро нарисовать свои мнемоники/проц
но лично я с ним вообще никогда не работал
