### ISSUE TITLE
Another ROM reading typo.

### ISSUE THREAD

**Issue by ilyakurdyukov** [azya52/BrickEmuPy#4]
Jump to the middle of the instruction, most likely there is a jump to 0x50D (one bit difference).

```
4FF:    ja1 50C                         ;8D0C
...
50B:    mov R1R0, 0x14                  ;5401
50D:    inc [R1R0]                      ;0C
```

**Comment by azya52** [comment]
You're right, there was a typo at this address, although there was a jump not to 0x50D but to 0x504. Thank you!  Fixed."
