### ISSUE TITLE
Can we borrow your svg for mame?

### ISSUE THREAD

**Issue by galibert** [azya52/BrickEmuPy#6]
Hi,

Haze is currently adding the emulation of the same device to Mame.  I see that you've done a beautiful svg for the device, would you agree that we use it in Mame too?

Best regards,

  Olivier Galibert

**Comment by azya52** [comment]
Hi, great news! Of course, I don’t mind.

**Comment by ilyakurdyukov** [comment]
@galibert by any chance, do you have alternative ROMs?

**Comment by galibert** [comment]
Sadly, the checksums tell me we have the same rom contents.

The driver has been added to master with the svg adapted for mame, much thanks.

**Comment by parkerlreed** [comment]
> Sadly, the checksums tell me we have the same rom contents.
> 
> The driver has been added to master with the svg adapted for mame, much thanks.

Where's the svg? I have the bin and srom in place but cannot find the graphics.

**Comment by parkerlreed** [comment]
Looks like I finally found the romset. Thanks!
