### ISSUE TITLE
Icons is missing on this released. Was showing before on the Nobara OS. No idea what happen.

### ISSUE THREAD

**Issue by Dunard** [azya52/BrickEmuPy#8]
No sounds still. I'm still testing on this Nobara OS.

I will try the Fedora OS out next. The one from the Rawhide 40. Just to test out to see the same issues are there.

![Screenshot_20240216_003038](https://github.com/azya52/BrickEmuPy/assets/31096423/060e4be5-c668-4a59-93fa-b9fc4a6fcb09)

Windows 11 Home no issue at all. :)

**Comment by Dunard** [comment]
ok the icons are there on the Fedora 41 (Which is odd on the version because the 40 isn't out yet.) 
![Screenshot_20240216_014915](https://github.com/azya52/BrickEmuPy/assets/31096423/76fd66d4-d360-4500-acbf-eecd3c789aed)

No sounds only.

Something ether got removed or an update broken the icons on the Nobara 39 OS. Still no idea.

**Comment by azya52** [comment]
No sounds for any of the games?

**Comment by Dunard** [comment]
Just the Windows have the sounds. None on Linux.

Tested on the Kubuntu 22.04.3. No sounds and the buttons are black.

Next up testing the Ubuntu 22.04.3 out. Probably have the same issue as the Nobara 39 and Kubuntu 22.04.3.

**Comment by Dunard** [comment]
I think the sounds should work when it connect to sdl or sdl2 on Linux.

**Comment by azya52** [comment]
Please check the latest commit.

**Comment by Dunard** [comment]
You got the icons fixed.
![Screenshot_20240219_012420](https://github.com/azya52/BrickEmuPy/assets/31096423/ce07e1dc-09cb-40f7-9f71-acbf6ec5823a)

:)

**Comment by azya52** [comment]
Does the sounds work? I tested the sounds on Ubuntu 22.04.3.

**Comment by Dunard** [comment]
Nobara-39-Official-2024-01-24 and Fedora-Workstation-Live-x86_64-39-1.5 no sounds. Competely ignore the 39 releases. There is a bug. Been fixed on the 40 beta.

Fedora-KDE-Live-x86_64-Rawhide-20240218 and ubuntu-22.04.3-desktop-amd64 got sounds.

**Comment by Dunard** [comment]
I found out this morning that the Fedora 39 and Nobara 39 is using an out of date QT5. Which is why it having this issue. Funny it's does run after the python3-pyqt6-devel installed.

**Comment by Dunard** [comment]
I got this fully working on the Distrobox. No issue. https://github.com/89luca89/distrobox

========================================

Create a container.

distrobox-create --name fedorabox --image fedora:rawhide

distrobox-create --name ubuntubox --image ubuntu:22.04

========================================

Load a container.

distrobox-enter --name fedorabox

distrobox-enter --name ubuntubox

========================================

Install these packages.

Fedora Rawhide. sudo dnf install python python3-pyqt6-devel qt6-qtbase

Ubuntu 22.04. sudo apt install libpulse0 python3-pip python3-pyqt6.sip qt6-base-dev && pip3 install pyqt6

========================================

Logout and then reload the Distrobox. This will get the BrickEmuPy to run better.

logout

========================================

Load the BrickEmuPy Emulator.

cd BrickEmuPy && python3 main.py

========================================

Remove a container. (Warning: This will perment delete container and files inside the container.)

distrobox stop fedorabox && distrobox rm fedorabox

distrobox stop ubuntubox && distrobox rm ubuntubox

**Comment by Dunard** [comment]
Got the sounds to work on the Nobara 39. Should work on the Fedora 39. Uploaded the QT updates and the Python updates here. https://mega.nz/folder/aBVSVQQD#vwIesJi9NrOi6k3_lbX0FA There is a command in the readme for installing the updates onto Nobara/Fedora 39.

Note: Update System will downgrade all back to the older version. Do not use this. Use this instead. sudo dnf upgrade --refresh

I took some time to find all these. :)

**Comment by Dunard** [comment]
GloriousEggroll added a ton of patches on his Nobara 39 last night. Now the sounds is working.

I removed the link to the files. Not needed now.
